APINames:
_softwareID       .equ 0
_versionID        .equ 1
_preInit          .equ 2
_beep             .equ 3
_convAToSeg       .equ 4
_regAToASCII      .equ 5
_ASCIItoSegment   .equ 6
_stringCompare    .equ 7
_HLToString       .equ 8
_AToString        .equ 9
_scanSegments     .equ 10
_displayError     .equ 11
_LCDBusy          .equ 12
_stringToLCD      .equ 13
_charToLCD        .equ 14
_commandToLCD     .equ 15
_scanKeys         .equ 16
_scanKeysWait     .equ 17
_matrixScan       .equ 18
_joystickScan     .equ 19
_serialEnable     .equ 20
_serialDisable    .equ 21
_txByte           .equ 22
_rxByte           .equ 23
_intelHexLoad     .equ 24
_sendToSerial     .equ 25
_receiveFromSerial .equ 26
_sendAssembly     .equ 27
_sendHex          .equ 28
_genDataDump      .equ 29
_checkStartEnd    .equ 30
_menuDriver       .equ 31
_paramDriver      .equ 32
_timeDelay        .equ 33
_playNote         .equ 34
_playTune         .equ 35
_playTuneMenu     .equ 36
_getCaps          .equ 37
_getShadow        .equ 38
_getProtect       .equ 39
_getExpand        .equ 40
_setCaps          .equ 41
_setShadow        .equ 42
_setProtect       .equ 43
_setExpand        .equ 44
_toggleCaps       .equ 45
_toggleShadow     .equ 46
_toggleProtect    .equ 47
_toggleExpand     .equ 48
_random           .equ 49
_setDisStart		.equ 50
_getDisNext		.equ 51
_getDisassembly		.equ 52
_matrixScanASCII	.equ 53
